default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: word_complexity_api_development

test:
  <<: *default
  database: word_complexity_api_test
